package com.medoq.backend.service;

import com.medoq.backend.dto.reservation.*;
import com.medoq.backend.entity.*;
import com.medoq.backend.exception.BusinessException;
import com.medoq.backend.exception.ResourceNotFoundException;
import com.medoq.backend.repository.*;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.security.access.AccessDeniedException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

@Service
@Slf4j
@RequiredArgsConstructor
public class ReservationService {

    private final ReservationRepository     reservationRepository;
    private final PharmacyRepository        pharmacyRepository;
    private final PharmacyUserRepository    pharmacyUserRepository;
    private final MedicationRepository      medicationRepository;
    private final PharmacyStockRepository   stockRepository;
    private final UserRepository            userRepository;
    private final NotificationService       notificationService;

    // ── Create ────────────────────────────────────────────────────

    @Transactional
    public ReservationResponse create(CreateReservationRequest req, UUID customerId) {
        // 1 — Load entities
        User customer = userRepository.findById(customerId)
                .orElseThrow(() -> new ResourceNotFoundException("User", customerId));

        Pharmacy pharmacy = pharmacyRepository.findById(req.pharmacyId())
                .orElseThrow(() -> new ResourceNotFoundException("Pharmacy", req.pharmacyId()));

        if (pharmacy.getStatus() != Pharmacy.Status.ACTIVE) {
            throw new BusinessException("This pharmacy is not currently accepting reservations.");
        }

        // 2 — Build items and compute total
        List<ReservationItem> items = new ArrayList<>();
        BigDecimal total = BigDecimal.ZERO;

        for (ReservationItemRequest itemReq : req.items()) {
            Medication medication = medicationRepository.findById(itemReq.medicationId())
                    .orElseThrow(() -> new ResourceNotFoundException("Medication", itemReq.medicationId()));

            PharmacyStock stock = stockRepository
                    .findByPharmacyIdAndMedicationId(pharmacy.getId(), medication.getId())
                    .orElseThrow(() -> new BusinessException(
                        medication.getName() + " is not available at " + pharmacy.getName()));

            if (!stock.isAvailable() || stock.getQuantity() <= 0) {
                throw new BusinessException(
                    medication.getName() + " is currently out of stock at " + pharmacy.getName());
            }
            if (stock.getQuantity() < itemReq.quantity()) {
                throw new BusinessException(
                    "Insufficient stock for " + medication.getName() +
                    ". Available: " + stock.getQuantity() + ", Requested: " + itemReq.quantity());
            }

            BigDecimal itemTotal = stock.getUnitPrice()
                    .multiply(BigDecimal.valueOf(itemReq.quantity()));
            total = total.add(itemTotal);

            items.add(ReservationItem.builder()
                    .medication(medication)
                    .quantity(itemReq.quantity())
                    .unitPrice(stock.getUnitPrice())
                    .build());
        }

        // 3 — Create reservation (reference generated by DB trigger)
        Instant now       = Instant.now();
        Instant expiresAt = now.plus(2, ChronoUnit.HOURS);

        Reservation reservation = Reservation.builder()
                .reference("")           // trigger fills this
                .customer(customer)
                .pharmacy(pharmacy)
                .status(Reservation.Status.PENDING)
                .totalAmount(total)
                .expiresAt(expiresAt)
                .pickupDate(req.pickupDate())
                .notes(req.notes())
                .build();

        // Link items to the reservation
        for (ReservationItem item : items) {
            item.setReservation(reservation);
        }
        reservation.setItems(items);

        reservation = reservationRepository.save(reservation);
        log.info("Reservation created: {} for customer: {}", reservation.getId(), customerId);

        return ReservationResponse.from(reservation);
    }

    // ── Read ──────────────────────────────────────────────────────

    @Transactional(readOnly = true)
    public ReservationResponse getById(UUID id, UUID requesterId, String requesterRole) {
        Reservation r = findWithDetails(id);
        assertCanView(r, requesterId, requesterRole);
        return ReservationResponse.from(r);
    }

    @Transactional(readOnly = true)
    public Page<ReservationResponse> getByPatient(
            UUID patientId, UUID requesterId, String requesterRole, Pageable pageable) {
        // Only the patient themselves or an admin can list patient reservations
        if (!requesterId.equals(patientId) && !isAdmin(requesterRole)) {
            throw new AccessDeniedException("Access denied to patient reservations.");
        }
        return reservationRepository
                .findByCustomerIdOrderByCreatedAtDesc(patientId, pageable)
                .map(ReservationResponse::from);
    }

    @Transactional(readOnly = true)
    public Page<ReservationResponse> getByPharmacy(
            UUID pharmacyId, UUID requesterId, String requesterRole, Pageable pageable) {
        assertPharmacyAccess(pharmacyId, requesterId, requesterRole);
        return reservationRepository
                .findByPharmacyIdOrderByCreatedAtDesc(pharmacyId, pageable)
                .map(ReservationResponse::from);
    }

    // ── Confirm (PENDING → CONFIRMED) ─────────────────────────────

    @Transactional
    public ReservationResponse confirm(UUID id, UUID pharmacyUserId, String requesterRole) {
        Reservation reservation = findWithDetails(id);

        assertPharmacyAccess(reservation.getPharmacy().getId(), pharmacyUserId, requesterRole);

        if (reservation.getStatus() != Reservation.Status.PENDING) {
            throw new BusinessException(
                "Only PENDING reservations can be confirmed. Current status: "
                + reservation.getStatus());
        }
        if (reservation.getExpiresAt().isBefore(Instant.now())) {
            // Already past expiry — expire it and reject
            reservation.setStatus(Reservation.Status.EXPIRED);
            reservationRepository.save(reservation);
            throw new BusinessException("Reservation has expired and cannot be confirmed.");
        }

        // Decrement stock for each item (pessimistic lock per item)
        for (ReservationItem item : reservation.getItems()) {
            int updated = stockRepository.decrementStock(
                reservation.getPharmacy().getId(),
                item.getMedication().getId(),
                item.getQuantity());

            if (updated == 0) {
                throw new BusinessException(
                    "Insufficient stock for " + item.getMedication().getName() +
                    ". Cannot confirm reservation.");
            }
        }

        reservation.setStatus(Reservation.Status.CONFIRMED);
        reservation.setConfirmedAt(Instant.now());
        // Extend expires_at from confirmation time — patient has 2 hours to pick up
        reservation.setExpiresAt(Instant.now().plus(2, ChronoUnit.HOURS));
        reservation = reservationRepository.save(reservation);

        notificationService.sendReservationConfirmed(reservation);
        log.info("Reservation confirmed: {} by pharmacy staff: {}",
            reservation.getId(), pharmacyUserId);

        return ReservationResponse.from(reservation);
    }

    // ── Cancel (any non-terminal → CANCELLED) ─────────────────────

    @Transactional
    public ReservationResponse cancel(UUID id, CancelRequest req,
                                       UUID requesterId, String requesterRole) {
        Reservation reservation = findWithDetails(id);

        assertCanModify(reservation, requesterId, requesterRole);

        if (reservation.getStatus().isTerminal()) {
            throw new BusinessException(
                "Reservation is already in a terminal state: " + reservation.getStatus());
        }

        boolean wasStockDecremented = reservation.getStatus().isStockDecremented();

        reservation.setStatus(Reservation.Status.CANCELLED);
        reservation.setCancelledAt(Instant.now());
        reservation.setCancellationReason(req != null ? req.reason() : null);
        reservation = reservationRepository.save(reservation);

        // Restore stock if decrement had already happened
        if (wasStockDecremented) {
            restoreStock(reservation);
        }

        notificationService.sendReservationCancelled(reservation);
        log.info("Reservation cancelled: {} by: {}", reservation.getId(), requesterId);

        return ReservationResponse.from(reservation);
    }

    // ── Complete (READY | CONFIRMED | PAID → COMPLETED) ───────────

    @Transactional
    public ReservationResponse complete(UUID id, UUID pharmacyUserId, String requesterRole) {
        Reservation reservation = findWithDetails(id);

        assertPharmacyAccess(reservation.getPharmacy().getId(), pharmacyUserId, requesterRole);

        var status = reservation.getStatus();
        if (status != Reservation.Status.READY
                && status != Reservation.Status.CONFIRMED
                && status != Reservation.Status.PAID) {
            throw new BusinessException(
                "Only READY, CONFIRMED, or PAID reservations can be completed. Current: " + status);
        }

        reservation.setStatus(Reservation.Status.COMPLETED);
        reservation.setCompletedAt(Instant.now());
        reservation = reservationRepository.save(reservation);

        log.info("Reservation completed: {}", reservation.getId());
        return ReservationResponse.from(reservation);
    }

    // ── Mark ready (CONFIRMED | PAID → READY) ─────────────────────
    // Exposed internally for the payment module; also used via complete flow.

    @Transactional
    public ReservationResponse markReady(UUID id, UUID pharmacyUserId, String requesterRole) {
        Reservation reservation = findWithDetails(id);

        assertPharmacyAccess(reservation.getPharmacy().getId(), pharmacyUserId, requesterRole);

        if (reservation.getStatus() != Reservation.Status.CONFIRMED
                && reservation.getStatus() != Reservation.Status.PAID) {
            throw new BusinessException(
                "Only CONFIRMED or PAID reservations can be marked READY. Current: "
                + reservation.getStatus());
        }

        reservation.setStatus(Reservation.Status.READY);
        reservation = reservationRepository.save(reservation);

        notificationService.sendReservationReady(reservation);
        log.info("Reservation marked READY: {}", reservation.getId());

        return ReservationResponse.from(reservation);
    }

    // ── Expiry job hooks (called by scheduler) ────────────────────

    /** Returns all PENDING reservations past their expiry for processing. */
    @Transactional(readOnly = true)
    public List<Reservation> findExpiredPending() {
        return reservationRepository.findExpiredPending(Instant.now());
    }

    @Transactional
    public void expireReservation(Reservation reservation) {
        if (reservation.getStatus() != Reservation.Status.PENDING) return;
        reservation.setStatus(Reservation.Status.EXPIRED);
        reservationRepository.save(reservation);
        notificationService.sendReservationExpired(reservation);
        log.debug("Reservation expired: {}", reservation.getId());
    }

    /** Returns PENDING reservations expiring within the next 35 minutes, warning not yet sent. */
    @Transactional(readOnly = true)
    public List<Reservation> findAboutToExpire() {
        Instant from = Instant.now().plus(25, ChronoUnit.MINUTES);
        Instant to   = Instant.now().plus(35, ChronoUnit.MINUTES);
        return reservationRepository.findPendingExpiringBetween(from, to);
    }

    @Transactional
    public void sendExpiryWarningFor(Reservation reservation) {
        notificationService.sendExpiryWarning(reservation);
        reservationRepository.markWarningSent(reservation.getId(), Instant.now());
    }

    // ── Private helpers ───────────────────────────────────────────

    private Reservation findWithDetails(UUID id) {
        return reservationRepository.findByIdWithDetails(id)
                .orElseThrow(() -> new ResourceNotFoundException("Reservation", id));
    }

    private void restoreStock(Reservation reservation) {
        for (ReservationItem item : reservation.getItems()) {
            int updated = stockRepository.incrementStock(
                reservation.getPharmacy().getId(),
                item.getMedication().getId(),
                item.getQuantity());
            if (updated == 0) {
                log.warn("Failed to restore stock for medication {} at pharmacy {}",
                    item.getMedication().getId(), reservation.getPharmacy().getId());
            }
        }
        log.debug("Stock restored for reservation: {}", reservation.getId());
    }

    private void assertCanView(Reservation r, UUID requesterId, String role) {
        boolean isCustomer = r.getCustomer().getId().equals(requesterId);
        boolean isPharmacy = isPharmacyStaff(r.getPharmacy().getId(), requesterId, role);
        if (!isCustomer && !isPharmacy && !isAdmin(role)) {
            throw new AccessDeniedException("You do not have access to this reservation.");
        }
    }

    private void assertCanModify(Reservation r, UUID requesterId, String role) {
        boolean isCustomer = r.getCustomer().getId().equals(requesterId);
        boolean isPharmacy = isPharmacyStaff(r.getPharmacy().getId(), requesterId, role);
        if (!isCustomer && !isPharmacy && !isAdmin(role)) {
            throw new AccessDeniedException("You cannot modify this reservation.");
        }
    }

    private void assertPharmacyAccess(UUID pharmacyId, UUID userId, String role) {
        if (isAdmin(role)) return;
        if (!isPharmacyStaff(pharmacyId, userId, role)) {
            throw new AccessDeniedException("You are not a staff member of this pharmacy.");
        }
    }

    private boolean isPharmacyStaff(UUID pharmacyId, UUID userId, String role) {
        if (isAdmin(role)) return true;
        return pharmacyUserRepository.existsByPharmacyIdAndUserId(pharmacyId, userId);
    }

    private boolean isAdmin(String role) {
        return "ADMIN".equals(role) || "ROLE_ADMIN".equals(role);
    }
}
